config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('sender.urls', namespace='sender')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    RegistrationView,
    LogoutView,
    ProfileView,
    ProfileUpdateView,
    VerifyEmailView,
    SuccessVerifyView,
    PasswordChangeView,
    PasswordRecoveryRequestView,
    PassRecoveryRequsetSuccess,
    UserListView,
    ChangeUserStatus,
)

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="sender:index"), name="logout"),
    path(
        "registrations/",
        RegistrationView.as_view(template_name="users/registration.html"),
        name="registration",
    ),
    path("profile/<int:pk>", ProfileView.as_view(), name="profile"),
    path("update/<int:pk>", ProfileUpdateView.as_view(), name="update"),
    path("verify_email/<int:pk>/", VerifyEmailView.as_view(), name="verify_email"),
    path("success_verify/", SuccessVerifyView.as_view(), name="success_verify"),
    path(
        "password_recovery_request/",
        PasswordRecoveryRequestView.as_view(),
        name="password_recovery_request",
    ),
    path(
        "password_recovery_request_success/",
        PassRecoveryRequsetSuccess.as_view(),
        name="password_recovery_request_success",
    ),
    path(
        "password_change/<int:pk>/",
        PasswordChangeView.as_view(),
        name="password_change",
    ),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("ban_user/<int:pk>", ChangeUserStatus.as_view(), name="ban_user"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True, verbose_name="Email")
    avatar = models.ImageField(upload_to="avatars", verbose_name="Аватар", blank=True)
    phone_number = models.CharField(
        max_length=11,
        verbose_name="Номер телефона",
        null=True,
        unique=True,
        blank=False,
    )
    country = models.CharField(
        verbose_name="Страна", null=True, blank=True, max_length=100
    )
    is_active = models.BooleanField(default=False, verbose_name="Активен")
    is_banned = models.BooleanField(default=False, verbose_name="Бан")
    is_staff = models.BooleanField(default=False, verbose_name="Сотрудник")
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_view_user_list", "Can view user list"),
            ("can_ban", "Can ban user"),
        ]

    def __str__(self):
        email_status = "Email не подтвержден"
        banned = "Активен"
        if self.is_active:
            email_status = "Email подтвержден"
        if self.is_banned:
            banned = "Заблокирован"

        return f"{self.username} - {self.email} | {email_status} | {banned}"

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ["email", "username", "password1", "password2"]
        labels = {
            "email": "E-mail",
            "username": "Имя пользователя",
            "password1": "Пароль",
            "password2": "Подтверждение пароля",
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Email"}
        )
        self.fields["username"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Имя пользователя"}
        )
        self.fields["password1"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Пароль"}
        )
        self.fields["password2"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Повторите пароль"}
        )


class CustomUserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["email", "username"]
        REQUIRED_FIELDS = []

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)

        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Email"}
        )
        self.fields["username"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Имя пользователя"}
        )


class CustomUserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)

        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Email"}
        )
        self.fields["password"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Пароль"}
        )

    def confirm_login_allowed(self, user):
        super().confirm_login_allowed(user)
        if not user.is_active:
            raise forms.ValidationError(
                "Ваш email не подтвержден. Пожалуйста, проверьте вашу почту.",
                code="email_not_verified",
            )
        if user.is_banned:
            raise forms.ValidationError(
                "Ваша учетная запись заблокирована.",
                code="banned",
            )


class PasswordRecoveryRequestForm(forms.Form):
    email = forms.EmailField()

    class Meta:
        model = CustomUser
        fields = ["email"]
        REQUIRED_FIELDS = []

    def __init__(self, *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)

        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Email"}
        )

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            CustomUser.objects.get(email=email)
            return email
        except Exception:
            raise forms.ValidationError("Пользователя с таким email не существует")


class PasswordChangeForm(forms.Form):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)

        self.fields["password1"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Новый пароль"}
        )
        self.fields["password2"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Новый пароль"}
        )

users/views.py
from pathlib import Path

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LogoutView
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView, FormView
from .forms import (
    CustomUserCreationForm,
    CustomUserUpdateForm,
    PasswordRecoveryRequestForm,
    PasswordChangeForm,
)
from .models import CustomUser
from sender.services import UserStatistic
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(dotenv_path=BASE_DIR / ".env")


class RegistrationView(CreateView):
    model = CustomUser
    template_name = "users/registration.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        verification_url = reverse_lazy("users:verify_email", kwargs={"pk": user.pk})
        absolute_url = self.request.build_absolute_uri(verification_url)
        email = form.cleaned_data.get("email")
        send_mail(
            subject="Регистрация на сайте",
            message=f"""Здравствуйте!
Вы зарегистрировались на сайте.
Для подтверждения email перейдите по ссылке:
{absolute_url}""",
            from_email=os.getenv("EMAIL_HOST_USER"),
            recipient_list=[email],
        )
        return super().form_valid(form)


class CustomLogoutView(LoginRequiredMixin, LogoutView):
    next_page = reverse_lazy("sender:index")


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "users/profile.html"
    login_url = reverse_lazy("users:login")

    def get_context_data(self, **kwargs):
        statistic = UserStatistic.get_user_statistic(kwargs["pk"])
        context = {
            "success_attempts": statistic[0],
            "fail_attempts": statistic[1],
            "sent_messages": statistic[2],
        }
        return context


class ProfileUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserUpdateForm
    login_url = reverse_lazy("users:login")

    def has_permission(self):
        if self.request.user.is_superuser or self.request.user == self.get_object():
            return True
        return HttpResponseForbidden(
            "У вас нет прав для изменения данных этого пользователя"
        )

    def get_success_url(self):
        return reverse_lazy("users:profile", kwargs={"pk": self.object.pk})

    template_name = "users/update.html"


class VerifyEmailView(View):
    def get(self, request, *args, **kwargs):
        user = CustomUser.objects.get(pk=self.kwargs["pk"])
        user.is_active = True
        user.save()
        return redirect(reverse_lazy("users:success_verify"))


class SuccessVerifyView(TemplateView):
    template_name = "users/success_verify.html"


class PasswordRecoveryRequestView(FormView):
    model = CustomUser
    template_name = "users/password_recovery_request.html"
    form_class = PasswordRecoveryRequestForm
    success_url = reverse_lazy("users:password_recovery_request_success")

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        user_pk = get_object_or_404(CustomUser, email=email)
        recovery_url = reverse_lazy("users:password_change", kwargs={"pk": user_pk.pk})
        absolute_url = self.request.build_absolute_uri(recovery_url)

        send_mail(
            subject="Восстановление пароля",
            message=f"""Для восстановления пароля пройдите по ссылке:
{absolute_url}
Если вы не запрашивали восстановление пароля, то проигнорируйте это письмо""",
            from_email=os.getenv("EMAIL_HOST_USER"),
            recipient_list=[email],
        )
        return redirect(reverse_lazy("users:password_recovery_request_success"))


class PassRecoveryRequsetSuccess(TemplateView):
    template_name = "users/password_recovery_request_success.html"


class PasswordChangeView(FormView):
    model = CustomUser
    template_name = "users/password_recovery.html"
    form_class = PasswordChangeForm
    success_url = reverse_lazy("users:login")

    def post(self, request, *args, **kwargs):
        user = get_object_or_404(CustomUser, pk=kwargs["pk"])
        print(user.email)
        user.set_password(request.POST.get("password1"))
        user.save()
        update_session_auth_hash(request, user)
        return redirect(reverse_lazy("users:login"))


@method_decorator(cache_page(60 * 15), name="dispatch")
class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = CustomUser
    template_name = "users/user_list.html"
    context_object_name = "user_list"
    login_url = reverse_lazy("users:login")
    permission_required = ("users.can_view_user_list",)


class ChangeUserStatus(LoginRequiredMixin, View):
    login_url = reverse_lazy("users:login")

    def post(self, request, pk):
        user = get_object_or_404(CustomUser, id=pk)
        if request.user.has_perm("sender.can_ban") and not user.is_superuser:
            user.is_banned = not user.is_banned
            user.save()
            if user.is_banned:
                email = user.email
                send_mail(
                    subject="Ваша учетная запись заблокирована",
                    message=f"Здравствуйте, {user.username}! К сожалению Ваша учетная запись была заблокирована.",
                    from_email=os.getenv("EMAIL_HOST_USER"),
                    recipient_list=[email],
                )
            return redirect(reverse_lazy("users:user_list"))
        return HttpResponseForbidden("У вас нет прав для блокировки этого пользователя")

users/templates/users/email_verify.html
{% extends 'sender/base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
<div class="alert alert-secondary" role="alert">
  Ваш email подтвержден! <a href="{% url 'sender:index' %}">На главную</a>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'sender/base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
<div align="center" style="padding-top: 35vh">
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Войти</button>
    <a href="{% url 'users:registration' %}" type="button" class="btn btn-outline-primary">Регистрация</a>
        <a href="{% url 'users:password_recovery_request' %}" type="button" class="btn btn-outline-primary">Восстановить пароль</a>
    </form>
</div>
{% endblock %}

users/templates/users/password_recovery.html
{% extends 'sender/base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
Форма восстановления пароля. Введите новый пароль.
<div align="center" style="padding-top: 35vh">
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>
{% endblock %}

users/templates/users/password_recovery_request.html
{% extends 'sender/base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
Форма восстановления пароля. Введите ваш email.
<div align="center" style="padding-top: 35vh">
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
</div>
{% endblock %}

users/templates/users/password_recovery_request_success.html
{% extends 'sender/base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
Запрос на восстановление пароля принят. Проверьте ваш email.
{% endblock %}

users/templates/users/profile.html
{% extends 'sender/base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
<p>{{ user.email }}</p>
<p>{{ user.username }}</p>
<p>Успешных попыток отправки: {{ success_attempts }}</p>
<p>Не успешных попыток отправки: {{ fail_attempts }}</p>
<p>Отправлено сообщений: {{ sent_messages }}</p>
<a href="{% url 'users:update' user.pk %}" type="button" class="btn btn-outline-primary">Изменить</a>
{% endblock %}

users/templates/users/registration.html
{% extends 'sender/base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
<div align="center" style="padding-top: 35vh">
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>
</div>
{% endblock %}

users/templates/users/success_verify.html
{% extends 'sender/base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
<div class="alert alert-secondary" role="alert">
  Ваш email подтвержден! <a href="{% url 'sender:index' %}">На главную</a>
</div>
{% endblock %}

users/templates/users/update.html
{% extends 'sender/base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
<div align="center" style="padding-top: 35vh">
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'sender/base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
<h1>Список пользователей</h1>
{% if user_list %}
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th scope="col">ID</th>
    <th scope="col">Имя пользователя</th>
    <th scope="col">Email</th>
    <th scope="col">Подтверждение email</th>
    <th scope="col">Статус</th>
    {% if perms.sender.can_ban %}
    <th scope="col"></th>
    {% endif %}
  </tr>
  </thead>
  <tbody>
  {% for user in user_list %}
  <tr>
    <th scope="col">{{ user.pk }}</th>
    <td>{{ user.username }}</td>
    <td>{{ user.email }}</td>
    <td>{% if user.is_active %}Подтвержден{% else %}Не подтвержден{% endif %}</td>
    <td>{% if user.is_banned %}Заблокирован{% else %}Активен{% endif %}</td>
    {% if perms.sender.can_ban %}
    <td>
      <form method="post" action="{% url 'users:ban_user' user.pk %}" style="padding-top: 10px">
        {% csrf_token %}
        {% if user.is_banned %}
        <button type="submit" class="btn btn-outline-success">Разблокировать</button>
        {% else %}
        <button type="submit" class="btn btn-outline-danger">Заблокировать</button>
        {% endif %}
      </form>
    </td>
    {% endif %}
  </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
Нет пользователей
{% endif %}
{% endblock %}